create table EMPLOYEES(
EMP_ID NUMERIC(4) NOT NULL,
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
JOB VARCHAR(9),
MGR VARCHAR(4),
HIRE_DATE DATE,
SALARY NUMERIC NOT NULL,
COMM_PCT NUMERIC(7,2),
DEPT_ID NUMERIC(2)
)

create table DEPARTMENTS(
DEPT_ID NUMERIC,
DEPT_NAME VARCHAR(20),
DEPT_LOC VARCHAR(20)
)